name: Update Submodules

on: 
  schedule:
    - cron: '*/6 * * * *'

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m "Update submodules"
        git push origin HEAD:${{ github.ref }}
