name: Update Submodules

on: 
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-from-sub-repo]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.BOT }}
    - name: Sync submodules
      run: git submodule sync
    - name: Update submodules
      run: git submodule update --init --recursive --remote
    - name: Ensure submodule branch
      run: |
        git submodule foreach 'git checkout main && git pull origin main'
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Update submodules"
          git push origin HEAD:refs/heads/main
        else
          echo "No changes to commit"
        fi
